### ISSUE TITLE
Make index.html more readeble

### ISSUE THREAD

**Issue by MistrAnonym** [MistrAnonym/openweb#14]
can someone make index.html more readeble?

**Comment by MistrAnonym** [comment]
sorry for my english

**Comment by mxjeonsg** [comment]
what do you mean "more readable"?? it's readable for me? maybe you mean "a little bit more stylish"? I mean, sure i can give it a glance in style but lmao

**Comment by mxjeonsg** [comment]
nvm, i just checked the github.io version instead of the 9e.cz, it looks great lol
maybe close this issue?

**Comment by MistrAnonym** [comment]
Ok
